import Vue from 'vue'

import './styles/quasar.styl'
import iconSet from 'quasar/icon-set/fontawesome-v5.js'
import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/material-icons/material-icons.css'
import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'
import {
  Quasar,
  //directives
  ClosePopup,
  Ripple,
  //plugins
  Notify,
  Dialog,
  QLinearProgress,
  //components
  QLayout,
  QHeader,
  QDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QIcon,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QFooter,
  QInput,
  QDialog,
  QCard,
  QCardSection,
  QCardActions,
  QTab,
  QRouteTab,
  QTabs,
  QTabPanel,
  QTabPanels,
  QSeparator,
  QImg,
  QPageSticky,
  QPageScroller,
  QSpinnerCube,
  QMenu,
  QSpace,
  QBar,
  QTooltip,
  QUploader,
  QEditor,
  QBadge,
  QAvatar,
  QCarousel,
  QCarouselControl,
  QCarouselSlide,
} from 'quasar'

Vue.use(Quasar, {
  config: {},
  components: {
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QFooter,
    QInput,
    QDialog,
    QCard,
    QCardSection,
    QCardActions,
    QTab,
    QRouteTab,
    QTabs,
    QTabPanel,
    QTabPanels,
    QSeparator,
    QImg,
    QPageSticky,
    QPageScroller,
    QSpinnerCube,
    QMenu,
    QSpace,
    QBar,
    QTooltip,
    QUploader,
    QEditor,
    QBadge,
    QLinearProgress,
    QAvatar,
    QCarousel,
    QCarouselControl,
    QCarouselSlide,
  },
  directives: {
    ClosePopup,
    Ripple,
  },
  plugins: {
    Notify,
    Dialog,
  },
  iconSet: iconSet
 })